FROM python:3.6-slim-buster
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
# ENTRYPOINT ["python"]
# CMD ["app.py"]
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0", "--debug=True"]
